### ISSUE TITLE
Mobs dont walk

### ISSUE THREAD

**Issue by ghost** [LeinneSW/EntityManager#4]
Mobs dont walk !??

can i make a problem by creating phar file ?

**Comment by ghost** [comment]
No Fix ?
Mobs don´t walk !?

**Comment by Erkam246** [comment]
Have you php7?

**Comment by Erkam246** [comment]
And that is not the Plugin for move entitys!

**Comment by Erkam246** [comment]
https://github.com/milk0417/PureEntities

**Comment by ghost** [comment]
Yes php7
PureEntities is installed.
Mobs walk yet but not jump :-)
Spiders can not climb and other animals and mobs can't jump

**Comment by ghost** [comment]
For Zombies and animals walk I need EntityManager and PureEntities or only Pure

**Comment by Erkam246** [comment]
PureEntitys for move entitys and Entitymanager for command exam : ent remove

**Comment by Erkam246** [comment]
PureEntitys = Entitys move
Entitymanager = commands

**Comment by ghost** [comment]
Ok thx 
Not jumping mobs a bug ?

**Comment by LeinneSW** [comment]
Mob's jump isn't implemented yet, sorry

**Comment by ghost** [comment]
Ohh :-( 
Spiders climb from mountain in a hole and run in the hole around the circle
