### ISSUE TITLE
If PHP5 can work?

### ISSUE THREAD

**Issue by wbh604** [LeinneSW/EntityManager#7]
I use ITX-Genisys, but plugins not work, it say Could not load plugin 'EntityManager': Incompatible API version,
i have try API2.0.0 and API1.14.0

**Comment by wbh604** [comment]
and i love you sir😂😂😂

**Comment by XiangZhao969** [comment]
Genisys doesn't support php5 anymore

**Comment by wbh604** [comment]
oh? dont you know ITX have PHP50.14?

**Comment by wbh604** [comment]
oh? dont you know ITX have PHP50.14?

**Comment by wbh604** [comment]
oh? dont you know ITX have PHP50.14?

**Comment by wbh604** [comment]
oh? dont you know ITX have PHP50.14?

**Comment by LeinneSW** [comment]
It is only support PHP 7
