### ISSUE TITLE
Are yours give up?

### ISSUE THREAD

**Issue by PoilZero** [LeinneSW/EntityManager#9]

**Comment by LeinneSW** [comment]
네. 이 프로젝트는 파기되었습니다
[PE-Nukkit](https://github.com/sw-team/PureEntities) 만 작업중입니다.

**Comment by PoilZero** [comment]
@milk0417 PE-Nukkit? Isn't that a developer's development program in China ?

**Comment by LeinneSW** [comment]
Nukkit은 중국에서 제작하는게 맞구요
PE는 PureEntities의 약자입니다
Nukkit은 자바라 자바로 넘어갔습니다
